using System.Windows;
using System.Windows.Controls;
using WPF_StudentsManager.Model;

namespace WPF_StudentsManager.Controls
{
    /// <summary>
    /// Interaction logic for StudentDetailControl.xaml
    /// </summary>
    public partial class StudentDetailControl : UserControl
    {
        private Student _student; //generated by propfull + Tab - part 1

        public StudentDetailControl()
        {
            InitializeComponent();
        }

        public Student Student //generated by propfull + Tab - part 2
        {
            get { return _student; }
            set
            {
                _student = value;
                txtFirstName.Text = _student?.FirstName ?? string.Empty; //student? if not null
                txtLastName.Text = _student?.LastName ?? string.Empty;
                chkIsActive.IsChecked = _student?.IsActive;
            }
        }

        private void TextBox_TextChanged(object sender, TextChangedEventArgs e)
        {
            UpdateStudent();
        }

        private void CheckBoxIsActive_Checked(object sender, RoutedEventArgs e)
        {
            UpdateStudent();
        }
        private void UpdateStudent()
        {
            if (Student != null) //if student is selected
            {
                Student.FirstName = txtFirstName.Text;
                Student.LastName = txtLastName.Text;
                Student.IsActive = chkIsActive.IsChecked.GetValueOrDefault(); //IsChecked property of chkIsActive is nullable bool (bool?)
                                                                              //so GetValueOrDefault() to default is false
            }
        }
    }
}
